### ISSUE TITLE
How to train Boundary Detection model?

### ISSUE THREAD

**Issue by duongttr** [jhuang448/LyricsAlignment-MTL#2]
Hi,

Currently, I'm using your repo to train my own dataset. I wonder how to train a boundary detection model while there's no file in your repo doing this task (there's only a file `train.py` for training the acoustic model).

Thank you very much!

**Comment by jhuang448** [comment]
Hi,

The script for boundary model training is not included in this repo. If you want to train your own, you could simply reuse the dataloader script and the acoustic model architecture, but replace the target with a boundary curve. You will need to obtain your boundary ground truth in some way, for example, from an energy function on the vocals. 

The boundary detection model is only used during alignment and does not have a huge impact on the overall alignment metrics. If you only want to get a working system, you might try the checkpoint in my repo. Although I have not tested on audio samples outside of DALI, I think that model would work in most cases, as it is not language-specific. (Please let me know whether it works on your dataset or not, if you tried!) Hope this helps.

Jiawen

**Comment by duongttr** [comment]
Thanks for your reply.

I will try using your pretrained boundary detection model on my system. I will response if it works well.
